#!/bin/bash

function errexit() {
    echo -e "$1"
    exit 1
}

function msgAndWait() {
    local msg=$1

    echo $msg
    echo "Hit enter to continue."
    read xxx
}

tmpDir=~/tmp/citadel-tmp
mkdir -p $tmpDir
cd $tmpDir

[ $EUID -eq 0 ] && sudo="" || sudo="sudo"

img="$tmpDir/$1"
[ "$img" == "" ] && errexit "? No IMG specified"

dest="$2"
[ "$dest" == "" ] && errexit "? No destination specified"

msgAndWait "Insert the USB key stick. Close dialog boxes when they pop up."

echo "Before umount"
echo ""
lsblk
$sudo umount /media/rkawala/*
echo ""
echo "After umount"
echo ""
lsblk

echo ""
msgAndWait "The SD card to be burned should be $dest. The USB key stick should be /dev/sdc. The MOUNTPOINTS column should be empty."

epoch_offset=$(date +%s)
echo "Disk label is $epoch_offset"
$sudo /usr/local/sdm/sdm-make-luks-usb-key /dev/sdc --init --mbr --fat --label $epoch_offset

echo ""
msgAndWait "Copy the keyfile path to the clipboard."

keyfilepath=$(wl-paste -n)
msgAndWait "Is $keyfilepath correct? Stop the script if not."

sudo parted $dest mklabel msdos

cmd="$sudo /usr/local/bin/sdm --burn $dest --host citadel --plugin cryptroot:crypto=aes|nopwd=y|no-expand-root=y|keyfile=$keyfilepath --burn-plugin parted:rootexpand=4096|addpartition=0,none --regen-ssh-host-keys --nowait-timesync --convert-root btrfs $img"

# This version creates one big Btrfs partition on the SD card. Both the OS and my home dir are in the same partition.
# cmd="$sudo /usr/local/bin/sdm --burn $dest --host citadel --plugin cryptroot:crypto=aes|nopwd=y|keyfile=$keyfilepath --expand-root --regen-ssh-host-keys --nowait-timesync --convert-root btrfs $img"

msgAndWait "About to do the burn: $cmd"
time $cmd

echo ""
echo "Ejecting /dev/sdc."
$sudo eject /dev/sdc
echo "Ejecting $dest."
$sudo eject $dest
