#!/bin/bash
#
# I started with ezsdm, then I made customizations from the gist at
# https://gist.github.com/andrewharle/0a0558a7438e6967f10c6e7b21efb7bd

. sdm-citadel-cmdsubs

make_my_citadel_tmpdir

[ $EUID -eq 0 ] && sudo="" || sudo="sudo"

img="$1"
[ "$img" == "" ] && errexit "? No IMG specified"

[ "$(type -t sdm)" == "" ] && errexit "? sdm is not installed"

ping_random

read -sp "Enter rkawala password: " user_pass
echo -e "\n**** REDACT THIS **** user_pass is $user_pass"
user_pass=$(mkpasswd --method=SHA-512 --rounds=4096 $user_pass)

#[ "$sudo" != "" ] && assets="." || assets="/etc/sdm/local-assets"
assets="."
rm -f $assets/my.plugins.1
[ -f $assets/my.plugins ] &&  mv $assets/my.plugins $assets/my.plugins.1

# Delete user pi if it exists
# Add citadel users.
cat > my-userlist <<EOF
deluser=pi
adduser=rkawala|password-hash=$user_pass|redact|uid=1000|groups=rkawala,users,adm,dialout,audio,netdev,video,plugdev,cdrom,games,input,gpio,spi,i2c,render,sudo,systemd-journal
adduser=git|password-hash=cannot-log-in-using-a-password|uid=1001|groups=git,users|nosudo|shell=/usr/bin/git-shell
EOF

(cat <<EOF
# Plugin List generated $(date +"%Y-%m-%d %H:%M:%S")
EOF
    ) | bash -c "cat >|$assets/my.plugins"

# Note that variable substitution will take place in this heredoc: $user_pass needs it
#
# Also note the docs say that the user plugin must be the first plugin(s) that run.
(cat <<EOF

user:userlist=./my-userlist

# Remove apps I don't want
apps:remove=vlc,rpi-connect,chromium

# I've removed some apps, but there are a bunch of dependencies that don't get deleted unless apt autoremove runs.
# Instead, time is wasted when the dependencies are updated. This phaseops thing forces an autoremove.
sdm.phaseops:ops=apt-autoremove

# Install apps
apps:name=mybrowsers|defer=firefox
apps:name=mytools|apps=keychain,lsof,iperf3,bind9-dnsutils,lz4

# I took this list from andrewharle's gist. I omitted overlayroot.
apps:name=coretools|apps=btrfs-progs,extrepo,git,apt-transport-https,nano,gpg,ca-certificates,apt-offline,apt-cacher-ng|defer=f2fs-tools,f3,systemd-container,whois,squashfs-tools,wl-clipboard,restic
apps:name=cryptoapps|defer=keepassxc
apps:name=encryption-drivers|apps=cryptsetup,cryptsetup-initramfs,busybox,systemd-cryptsetup

# Configure network manually once the image boots. SDM is capable of doing
# the config, but I'm keeping it simple for now.

# This configuration eliminates the need for piwiz so disable it
# I don't use Bluetooth on my citadel, and it's a possible security problem, so disable it.
disables:"piwiz|bluetooth|cloudinit"

# Uncomment to enable trim on all disks
# https://github.com/gitbls/sdm/blob/master/Docs/Plugins.md#trim-enable
#trim-enable

# Configure localization settings to the same as this system
# https://github.com/gitbls/sdm/blob/master/Docs/Plugins.md#l10n
L10n:"keymap=us|locale=en_US.UTF-8|timezone=America/Los_Angeles|wificountry=US"

# Make log files persistent
system:"journal=persistent"

# Set up my network
network:"nmconf=/etc/NetworkManager/NetworkManager.conf|nmconn=/etc/NetworkManager/system-connections/TP-LINK_5Ghz_062869.nmconnection,/etc/NetworkManager/system-connections/TP-Link_5GHz_CF37E4.nmconnection"

EOF
    ) | bash -c "cat >>$assets/my.plugins"

rm -f $img
echo "Extracting $img"
time unxz -k $img.xz
chmod 600 $img
echo ""

echo "--apt-dist-upgrade is turned on"
echo "--redact is turned off"

time $sudo /usr/local/bin/sdm --customize $img --plugin @$assets/my.plugins --extend --xmb 1024 --restart --regen-ssh-host-keys --showapt --aptcache localhost --apt-dist-upgrade
